apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxMachineTemplate
metadata:
  # the german numeral suffix at the end is used to differentiate machine templates
  # within the same kubernetes release, since they should not be modified
  # see https://cluster-api.sigs.k8s.io/tasks/updating-machine-templates.html
  name: nekropolis-control-plane-1.34.6-eins
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 20
      format: qcow2
      full: true
      memoryMiB: 8000
      network:
        networkDevices:
          - bridge: vmbr0
            defaultIPv4: true
            defaultIPv6: true
            model: virtio
            name: net0
      numCores: 2
      numSockets: 2
      pool: k8s-vms-nekropolis
      sourceNode: pve020
      templateID: 112
