apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: perses
spec:
  # NOTE: The helmchart expects the secret keys to be in kebab-case due to a hardcoded filter
  data:
    # this needs to be exactly 32 byte 
    # TODO: figure out how to cleanly use the whole entropy of the ASCII space, and not just
    # base64 (which  is a subset)
    # see https://perses.dev/perses/docs/configuration/configuration/#security-config
    # regenerate via  the following command
    # (openssl generates 24 random (pssobily unprintable) bytes, and base64 encodes those, which results in 4/3 fold amount of characters, i.e. 32 )
    # bao kv put -mount=kv nekropolis/perses/perses PERSES_SECURITY_ENCRYPTION_KEY=$(openssl rand -base64 24 )
    - secretKey: perses-security-encryption-key
      remoteRef:
        key: kv/nekropolis/perses/perses
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
        property: PERSES_SECURITY_ENCRYPTION_KEY
    # could not get the keyfile to work with raw openssl bytes yet
    # comment out until then
    #
    # 32 raw random bytes, base64-encoded for storage in openbao.
    # generate via:
    # openssl rand 32 | bao kv patch -mount=kv nekropolis/perses/perses PERSES_ENCRYPTION_KEY_RAW=-
    #- secretKey: perses-security-encryption-key-raw
    #  remoteRef:
    #    key: kv/nekropolis/perses/perses
    #    metadataPolicy: None
    #    conversionStrategy: Default
    #    decodingStrategy: None
    #    property: PERSES_SECURITY_ENCRYPTION_KEY_RAW
    #- secretKey: perses-security-encryption-key-file
    #  remoteRef:
    #    key: kv/nekropolis/perses/perses
    #    metadataPolicy: None
    #    conversionStrategy: Default
    #    decodingStrategy: None
    #    property: PERSES_SECURITY_ENCRYPTION_KEY_FILE
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: perses
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
