apiVersion: v1
kind: ServiceAccount
metadata:
  name: anubispaulista
  # this is where the SA exists (because SAs are namespaced)
  # it has nothing to do with where permissions are granted
  namespace: rbac-admin