# https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-logs-cluster/values.yaml 
# https://docs.victoriametrics.com/helm/victoria-logs-cluster/

fullnameOverride: victoria-logs

# apparently, vmauth serves as some kind of a loadbalancer for the ingesters and query api endpoints
vmauth:
  enabled: true

  # TODO: let's see if using an https ingress fixes our issue with directURL access
#  service:
#    type: LoadBalancer
#    annotations:
#      kube-vip.io/loadbalancerIPs: 192.168.13.11

  # we don't want the secret to be templated
  # so we use an existing secret managed by an ExternalSecret
  configSecretName: vmauth-config
  ingress:
    enabled: true
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: "local-ca-issuer"
      kube-vip.io/loadbalancerIPs: 192.168.13.11
    hosts:
      - name: victoria-logs.nekropolis.irminsul
        path:
          - /
        port: http
    tls:
      - secretName: victoria-logs-vmauth-certificate
        hosts:
          - victoria-logs.nekropolis.irminsul
  
# since we use vmauth, we don't need to talk to these two
vlinsert:
  service:
    clusterIP: None
    type: ClusterIP
vlselect:
  service:
    clusterIP: None
    type: ClusterIP

vlstorage:
  replicaCount: 2
  persistentVolume:
    size: 15Gi
  retentionPeriod: 21d
