apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-denkarium
  #this finaliser causes cascading deletion (delete children)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: wiki-denkarium
    server: "https://kubernetes.default.svc"
  project: tand-nippes-kinkerlitzchen-elaborat
  source:
    path: manifests/wiki-denkarium
    repoURL: "https://github.com/MausoleumManagement/wikis.git"
    targetRevision: master
