apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmauth-config
spec:
  data:
    - secretKey: auth.yml
      remoteRef:
        key: kv/nekropolis/victoria-metrics/vmauth-config
        property: auth.yml
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: vmauth-config
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
