apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-openbao
spec:
  instances: 3

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: cnpg-openbao-backups
  backup:
    target: prefer-standby


  superuserSecret:
    name: cnpg-openbao-superuser

  bootstrap:
    initdb:
      database: openbao
      owner: openbao
      secret:
        name: cnpg-openbao-app-user
  storage:
    size: 10Gi
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cnpg-openbao-backups
spec:
  # TODO: think about what we want here
  #retentionPolicy:
  configuration:
    # should be in the format of e.g.
    # endpointURL: bucket.us-east1.linodeobjects.com
    # destinationPath: "s3://BUCKET_NAME/path/to/folder"
    # TODO: we want to use https for this...
    endpointURL: http://garage.irminsul:3900
    destinationPath: "s3://openbao-backups/"
    #endpointCA:
    s3Credentials:
      accessKeyId:
        name: s3-backup-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: s3-backup-credentials
        key: ACCESS_SECRET_KEY
      region:
        name: s3-backup-credentials
        key: REGION