apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-openbao
spec:
  instances: 3

  backup:
    barmanObjectStore:
      # should be in the format of e.g.
      # endpointURL: bucket.us-east1.linodeobjects.com
      # destinationPath: "s3://BUCKET_NAME/path/to/folder"
      endpointURL: garage.irminsul:3900
      destinationPath: "s3://openbao-backups/"
      s3Credentials:
        accessKeyId:
          name: s3-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-backup-credentials
          key: ACCESS_SECRET_KEY

  superuserSecret:
    name: cnpg-openbao-superuser

  bootstrap:
    initdb:
      database: openbao
      owner: openbao
      secret:
        name: cnpg-openbao-app-user
  storage:
    size: 10Gi
