# https://docs.victoriametrics.com/helm/victoria-logs-collector/
# https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-logs-collector/values.yaml


remoteWrite:
  - url: "http://victoria-logs-vmauth.victoria-logs.svc.cluster.local:8427"
    # if remote is unavailable, store at most this much log data before discarding oldest
    maxDiskUsagePerURL: 10GB
