apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# https://github.com/tinkerbell/tinkerbell/tree/main/helm/tinkerbell
helmCharts:
  - name: tinkerbell
    namespace: tinkerbell
    releaseName: tinkerbellrelease
    repo: oci://ghcr.io/tinkerbell/charts
    valuesFile: values.yaml
    version: v0.23.0
resources:
  - namespace.yaml