apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-test-mechanicum
spec:
  cluster:
    name: cnpg-wiki-mechanicum
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
