# https://external-secrets.io/latest/provider/openbao/
# https://external-secrets.io/latest/provider/hashicorp-vault/
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-backend
spec:
  provider:
    vault:
      # TODO: we want to use https  in the long run
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "kv"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: nekropolis-external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
