  # https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium
  # CAUTION, the helm reference does not contain all the values
  # https://docs.cilium.io/en/stable/helm-reference/

# if we want to use istio with cilium, we need to configure these values
#cni:
#  # istio needs this to be set, otherwise cilium will clean up istios CNI-plugin
#  # https://istio.io/latest/docs/ambient/install/platform-prerequisites/#cilium
#  exclusive: false
#
#socketLB:
#  # cilium suggests to set the following when using istio
#  # otherwise istio  can't intercept network traffic
#  # https://docs.cilium.io/en/latest/network/servicemesh/istio/
#  enabled: true
#  hostNamespaceOnly: true

hubble:
  enabled: true
  # as per its description, this value is required when using hubble relay
  # https://github.com/cilium/cilium/issues/13537
  listenAddress: ":4244"
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: false

# 20260209 - did not seem to work out of the box; SPIRE server was unable to find / create his SQLite DB in his PV
# not sure whether this is related to a flaw in our storage setup, maybe test again with a different storage class?
# https://docs.cilium.io/en/stable/network/servicemesh/mutual-authentication/mutual-authentication/#installation
# BEGIN mTLS
#authentication:
#  enabled: true
#  mutual:
#    spire:
#      enabled: true
#      install:
#        enabled: true
# END mTLS
  

  
# settings for using the Gateway API
# see our (and their) docs for more info
kubeProxyReplacement: true
l7Proxy: true
gatewayAPI:
  enabled: true

envoy:
  enabled: true
  idleTimeoutDurationSeconds: 20

# create pod CIDR routes between worker nodes
# we could use this together with native routing so that we can route
# traffic from any node to a given pod IP
# only downside seems to be, that the routes are only created on worker nodes
# kube-vip runs on our control plane nodes however...
# this looks like a prime candidate for disentanglement
# maybe we can have a separate DS for the workers
#autoDirectNodeRoutes: true

k8sServiceHost: 192.168.10.11
k8sServicePort: 6443

routingMode: tunnel
# geneve seems to be the more modern protocol compared to vxlan
tunnelProtocol: geneve

loadBalancer:
  # this uses direct server return (DSR) for TCP packets and SNAT for UDP
  # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#hybrid-mode
  # the difference is, that SNAT will not pass on the source IP they way DSR does via geneve
  # but since UDP is stateless, sending the source IP each time (rather than just once on the SYN packet
  # in TCP would incur more costs, so we can see wheter we have any UDP services that benefit from knowing
  # the source IP and enable DSR for UDP whenever that happens;
  # we can also specify it per service using the lbModeAnnotation feature [see below])
  mode: hybrid
  # how will the source IP be passed 
  dsrDispatch: geneve
  l7:
    algorithm: "round_robin"
    backend: envoy
    # if we wanted to apply l7 load balancing to all services
    # exposing these ports, here's how that would work
    #ports: [80, 443]
# bpf:
  # this allows modifying the loadbalancing mode  (SNAT / DSR) per service via
  # the service.cilium.io/forwarding-mode annotation
  # but apparently, it doesn't work with hybrid loadbalancing mode
  # lbModeAnnotation: true

ingressController:
  enabled: true
  enforceHttps: true
  default: true
  # defaults + kubevip related annotations for declaratively defining LB IPs
  ingressLBAnnotationPrefixes:
    - "lbipam.cilium.io"
    - "nodeipam.cilium.io"
    - "service.beta.kubernetes.io"
    - "service.kubernetes.io"
    - "cloud.google.com"
    - "kube-vip.io"

# this would only be needed if we wanted to partially replace the kube-proxy
#nodePort:
#  enabled: true
