apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-token-service
spec:
  secretName: harbor-certificate-token-service
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "token-service.harbor.nekropolis.irminsul"
