apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor
spec:
  secretName: harbor-certificate
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "harbor.nekropolis.irminsul"
