apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core
spec:
  data:
    # generate something
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: kv/nekropolis/harbor/harbor-core
        property: HARBOR_ADMIN_PASSWORD
    # needs to be a 16 char string
    - secretKey: secretKey
      remoteRef:
        key: kv/nekropolis/harbor/harbor-core
        property: secretKey
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-core
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
