apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core
spec:
  data:
    # generate something
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: kv/nekropolis/harbor/harbor-core
        property: HARBOR_ADMIN_PASSWORD
    # needs to be a 16 char string
    - secretKey: secretKey
      remoteRef:
        key: kv/nekropolis/harbor/harbor-core
        property: secretKey
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/harbor-core
        property: REDIS_PASSWORD
    # another 16 char string used for who knows what
    - secretKey: secret
      remoteRef:
        key: kv/nekropolis/harbor/harbor-core
        property: secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-core
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
spec:
  data:
    # no clue what this is for
    # generate a 16 char string
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: kv/nekropolis/harbor/harbor-registry
        property: REGISTRY_HTTP_SECRET
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        key: kv/nekropolis/harbor/harbor-registry
        property: REGISTRY_PASSWD
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        key: kv/nekropolis/harbor/harbor-registry
        property: REGISTRY_HTPASSWD
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-core
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-jobservice
spec:
  data:
    # 16 char string
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: kv/nekropolis/harbor/harbor-jobservice
        property: JOBSERVICE_SECRET
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
    - secretKey: 
      remoteRef:
        key: kv/nekropolis/harbor/
        property: 
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-core
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
