apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core
spec:
  data:
    # Admin password for Harbor web UI
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-core
        metadataPolicy: None
        property: HARBOR_ADMIN_PASSWORD
    # 16 char string for secretKey
    - secretKey: secretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-core
        metadataPolicy: None
        property: secretKey
    # 16 char string for secret (different from secretKey)
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-core
        metadataPolicy: None
        property: secret
    # XSRF protection key (32 char string)
    - secretKey: XSRF_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-core
        metadataPolicy: None
        property: XSRF_KEY
# TODO: we should handle this via cert-manager
#    # TLS certificate for token encryption/decryption
#    - secretKey: tls.crt
#      remoteRef:
#        key: kv/nekropolis/harbor/harbor-core
#        property: tls.crt
#    # TLS key for token encryption/decryption
#    - secretKey: tls.key
#      remoteRef:
#        key: kv/nekropolis/harbor/harbor-core
#        property: tls.key
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-core
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-jobservice
spec:
  data:
    # TODO: We should look at getting rid of this duplication of secrets,
    # even if we are getting them from openbao
    # Registry password
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_PASSWD
    # Registry htpasswd
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_HTPASSWD
    # 16 char string for jobservice secret
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-jobservice
        metadataPolicy: None
        property: JOBSERVICE_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-jobservice
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
#---
#apiVersion: external-secrets.io/v1
#kind: ExternalSecret
#metadata:
#  name: harbor-nginx
#spec:
#  data:
#    # TODO: we should handle this via cert-manager
##    # CA certificate for Harbor internal TLS
##    - secretKey: ca.crt
##      remoteRef:
##        key: kv/nekropolis/harbor/harbor-nginx
##        property: ca.crt
##    # TLS certificate for nginx
##    - secretKey: tls.crt
##      remoteRef:
##        key: kv/nekropolis/harbor/harbor-nginx
##        property: tls.crt
##    # TLS key for nginx
##    - secretKey: tls.key
##      remoteRef:
##        key: kv/nekropolis/harbor/harbor-nginx
##        property: tls.key
#  secretStoreRef:
#    kind: ClusterSecretStore
#    name: openbao-backend
#  target:
#    name: harbor-nginx
#  refreshPolicy: Periodic
#  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
spec:
  data:
    # 16 char string for registry HTTP secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_HTTP_SECRET
    # Registry password
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_PASSWD
    # Registry htpasswd
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_HTPASSWD
    # Redis password for registry cache
    - secretKey: REGISTRY_REDIS_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_REDIS_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-registry
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registryctl
spec:
  data:
    # Registry control secret (16 char string)
    - secretKey: REGISTRYCTL_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registryctl
        metadataPolicy: None
        property: REGISTRYCTL_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-registryctl
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-trivy
spec:
  data:
    # GitHub token for Trivy vulnerability DB updates (can be empty)
    - secretKey: gitHubToken
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-trivy
        metadataPolicy: None
        property: gitHubToken
    # Redis connection URL for Trivy
    - secretKey: redisURL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-trivy
        metadataPolicy: None
        property: redisURL
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-trivy
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-harbor-standard-user
spec:
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-db-standard-user
        metadataPolicy: None
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-db-standard-user
        metadataPolicy: None
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: cnpg-harbor-standard-user
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-harbor-superuser
spec:
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-db-superuser
        metadataPolicy: None
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-db-superuser
        metadataPolicy: None
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: cnpg-harbor-superuser
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
