apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core
spec:
  data:
    # Admin password for Harbor web UI
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-core
        metadataPolicy: None
        property: HARBOR_ADMIN_PASSWORD
    # 16 char string for secretKey
    - secretKey: secretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-core
        metadataPolicy: None
        property: secretKey
    # 16 char string for secret (different from secretKey)
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-core
        metadataPolicy: None
        property: secret
    # XSRF protection key (32 char string)
    - secretKey: XSRF_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-core
        metadataPolicy: None
        property: XSRF_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-core
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-jobservice
spec:
  data:
    # TODO: We should look at getting rid of this duplication of secrets,
    # even if we are getting them from openbao
    # Registry password
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_PASSWD
    # 16 char string for jobservice secret
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-jobservice
        metadataPolicy: None
        property: JOBSERVICE_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-jobservice
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
spec:
  target:
    name: harbor-registry
    # by using a template, we can use a go template to derive the htpasswd content
    # from the provided username and password
    # https://external-secrets.io/latest/guides/templating/
    template:
      engineVersion: v2
      data:
        REGISTRY_HTTP_SECRET: "{{ .REGISTRY_HTTP_SECRET }}"
        REGISTRY_USERNAME: "{{ .REGISTRY_USERNAME }}"
        REGISTRY_PASSWD: "{{ .REGISTRY_PASSWD }}"
        REGISTRY_HTPASSWD:  "{{ htpasswd .REGISTRY_USERNAME .REGISTRY_PASSWD }}"
        REGISTRY_REDIS_PASSWORD: "{{ .REGISTRY_REDIS_PASSWORD }}"
  data:
    # 16 char string for registry HTTP secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_HTTP_SECRET
    # Registry Username (we duplicate this here so that we can derive htpasswd from it)
    # it is also passed via the values and then used by clients of the registry
    - secretKey: REGISTRY_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_USERNAME
    # Registry password
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_PASSWD
    # Redis password for registry cache
    - secretKey: REGISTRY_REDIS_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registry
        metadataPolicy: None
        property: REGISTRY_REDIS_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registryctl
spec:
  data:
    # Registry control secret (16 char string)
    - secretKey: REGISTRYCTL_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-registryctl
        metadataPolicy: None
        property: REGISTRYCTL_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-registryctl
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-trivy
spec:
  data:
    # GitHub token for Trivy vulnerability DB updates (can be empty)
    - secretKey: gitHubToken
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-trivy
        metadataPolicy: None
        property: gitHubToken
    # Redis connection URL for Trivy
    - secretKey: redisURL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-trivy
        metadataPolicy: None
        property: redisURL
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: harbor-trivy
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-harbor-standard-user
spec:
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-db-standard-user
        metadataPolicy: None
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-db-standard-user
        metadataPolicy: None
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: cnpg-harbor-standard-user
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-harbor-superuser
spec:
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-db-superuser
        metadataPolicy: None
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/nekropolis/harbor/harbor-db-superuser
        metadataPolicy: None
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: cnpg-harbor-superuser
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
