apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openstack-resource-controller
resources:
- https://github.com/k-orc/openstack-resource-controller/releases/download/v2.6.0/install.yaml
# the kustomization comes with its own namespace manifest
#- namespace.yaml
