# https://external-secrets.io/latest/api/externalsecret/


apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-example
spec:
  # this defines, how the stuff from openbao goes into the created secret
  data:
    - secretKey: cake-recipe-in-the-created-secret
      # where is the thingy in the secret store
      remoteRef:
        key: kv/nekropolis/xyz/abc-in-the-secret-store
        # which value
        property: cake-recipe
      # define which secret store we can get the secret from
      # we can break this down on a per-secret basis, if we want to
      # sourceRef:
        # ...
  # this is the default secret store that will be used for each
  # secretKey, that does not have its own sourceRef
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  # where the data will be put into, only one target per ExternalSecret
  target:
    # what name will the created secret have?
    name: example-sync
  # update the secret automatically
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
  # if we want to, we can use templating to decide how our secret will look like
  # template:
    #  ...
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-example
spec:
  # looks like you can also grab multiple values in a single statement
  # multiple entries can be added, which will be merged in a single secret
  # apparently this means we need to use extract: and find:
  # look at the docs for that, can't be bothered to explain this atm
  dataFrom:
