apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-example
spec:
  data:
    - secretKey: cake-recipe-in-the-created-secret
      remoteRef:
        key: kv/nekropolis/xyz/abc-in-the-secret-store
        property: cake-recipe
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: example-sync
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
