apiVersion: v1
kind: Namespace
metadata:
  name: perses
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: iam
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
---
apiVersion: v1
data:
  config.yaml: |2-

    api_prefix: ""
    database:
      file:
        extension: json
        folder: /perses
    frontend:
      explorer:
        enable: true
      important_dashboards: []
      information: ""
    provisioning:
      folders:
      - /etc/perses/provisioning
      interval: 10m
    security:
      cookie:
        same_site: lax
        secure: true
      enable_auth: false
      readonly: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: configuration
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
---
apiVersion: v1
data:
  datasource-victoria-logs.yaml: |-
    kind: "Datasource"
    metadata:
      name: "victoria-logs-nekropolis"
      project: "nekropolis"
    spec:
      default: true
      plugin:
        kind: "VictoriaLogsDatasource"
        spec:
          directUrl: "http://victoria-logs-vmauth.victoria-logs.svc.cluster.local:8427"
  global-datasource.yaml: |-
    kind: "GlobalDatasource"
    metadata:
      name: PrometheusDemo
    spec:
      # If true, then it's the default datasource for the type defined in the plugin.
      default: true
      plugin:
        # The type of the datasource. For example, `PrometheusDatasource`
        kind: PrometheusDatasource
        # The actual definition of the datasource. It will depend on the type defined in the previous field `kind`
        spec:
          directUrl: https://demo.promlabs.com
  project.yaml: |-
    kind: Project
    metadata:
      name: nekropolis
    spec:
      display:
      name: "nekropolis"
kind: ConfigMap
metadata:
  name: perses-provisioning-m4dckhdkc4
  namespace: perses
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: networking
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: perses
    app.kubernetes.io/name: perses
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: workload
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: perses
      app.kubernetes.io/name: perses
  serviceName: perses-headless
  template:
    metadata:
      annotations:
        checksum/config: 98ca4cda60c00d4a0680921242e43bf00581e647503c9eefcb4f97f79611cc21
      labels:
        app.kubernetes.io/instance: perses
        app.kubernetes.io/name: perses
    spec:
      containers:
      - args:
        - --config=/etc/perses/config/config.yaml
        - --web.listen-address=:8080
        - --web.hide-port=false
        - --web.telemetry-path=/metrics
        - --log.level=info
        - --log.method-trace=true
        env:
        - name: PERSES_SECURITY_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: perses-security-encryption-key
              name: perses
        image: docker.io/persesdev/perses:v0.53.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: perses
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/perses/provisioning
          name: perses-provisioning
        - mountPath: /etc/perses/config
          name: config
        - mountPath: /perses
          name: data
      securityContext:
        fsGroup: 2000
      serviceAccountName: perses
      volumes:
      - configMap:
          name: perses-provisioning-m4dckhdkc4
        name: perses-provisioning
      - name: data
        persistentVolumeClaim:
          claimName: perses
      - configMap:
          defaultMode: 420
          name: perses
        name: config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: perses
  namespace: perses
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/nekropolis/perses/perses
      metadataPolicy: None
      property: PERSES_SECURITY_ENCRYPTION_KEY
    secretKey: perses-security-encryption-key
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: perses
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    kube-vip.io/loadbalancerIPs: 192.168.13.10
  name: perses
  namespace: perses
spec:
  ingressClassName: cilium
  rules:
  - host: perses.nekropolis.irminsul
    http:
      paths:
      - backend:
          service:
            name: perses
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - perses.nekropolis.irminsul
    secretName: perses-certificate
