apiVersion: v1
kind: Namespace
metadata:
  name: perses
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: iam
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
---
apiVersion: v1
data:
  config.yaml: |2-

    api_prefix: ""
    database:
      file:
        extension: json
        folder: /perses
    frontend:
      explorer:
        enable: true
      important_dashboards: []
      information: ""
    provisioning:
      folders:
      - /etc/perses/provisioning
      interval: 10m
    security:
      cookie:
        same_site: lax
        secure: true
      enable_auth: false
      readonly: false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: configuration
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
---
apiVersion: v1
data:
  datasource-victoria-logs-directurl.yaml: |
    # see here for some examples and explanations
    # https://perses.dev/plugins/docs/victorialogs/model/#victorialogsdatasource
    kind: "Datasource"
    metadata:
      name: "victoria-logs-nekropolis-directurl"
      project: "nekropolis"
    spec:
      default: true
      plugin:
        kind: "VictoriaLogsDatasource"
        spec:
          # note, that directURL means, that our browser will directly query the datasource
          # if we want perses to make requests on our behalf, we need to use "proxy:"
          # TODO: Pros and Cons
          #proxy: "http://victoria-logs-vmauth.victoria-logs.svc.cluster.local:8427"
          directUrl: "https://victoria-logs.nekropolis.irminsul"
  datasource-victoria-logs-proxy.yaml: |+
    # see here for some examples and explanations
    # https://perses.dev/plugins/docs/victorialogs/model/#victorialogsdatasource
    kind: Datasource
    metadata:
        name: victoria-logs-nekropolis-proxy
        project: nekropolis
    spec:
        default: false
        plugin:
            kind: VictoriaLogsDatasource
            spec:
                proxy:
                    kind: HTTPProxy
                    spec:
                        allowedEndpoints:
                            - endpointPattern: /select/logsql/stats_query
                              method: POST
                            - endpointPattern: /select/logsql/stats_query_range
                              method: POST
                            - endpointPattern: /select/logsql/field_names
                              method: POST
                            - endpointPattern: /select/logsql/field_values
                              method: POST
                            - endpointPattern: /select/logsql/tail
                              method: POST
                            - endpointPattern: /select/logsql/query
                              method: POST
                            - endpointPattern: /select/logsql/hits
                              method: POST
                            - endpointPattern: /select/logsql/facets
                              method: POST
                            - endpointPattern: /select/logsql/stream_ids
                              method: POST
                            - endpointPattern: /select/logsql/streams
                              method: POST
                            - endpointPattern: /select/logsql/stream_field_names
                              method: POST
                            - endpointPattern: /select/logsql/stream_field_values
                              method: POST
                        url: http://victoria-logs-vmauth.victoria-logs.svc.cluster.local:8427


  global-datasource.yaml: |-
    kind: "GlobalDatasource"
    metadata:
      name: PrometheusDemo
    spec:
      # If true, then it's the default datasource for the type defined in the plugin.
      default: true
      plugin:
        # The type of the datasource. For example, `PrometheusDatasource`
        kind: PrometheusDatasource
        # The actual definition of the datasource. It will depend on the type defined in the previous field `kind`
        spec:
          directUrl: https://demo.promlabs.com
  project.yaml: |-
    kind: Project
    metadata:
      name: nekropolis
    spec:
      display:
      name: "nekropolis"
  variable.yaml: |+
    kind: Variable
    metadata:
        name: namespace
        project: nekropolis
    spec:
        kind: ListVariable
        spec:
            allowAllValue: false
            allowMultiple: false
            sort: none
            plugin:
                kind: VictoriaLogsFieldValuesVariable
                spec:
                    datasource:
                        kind: VictoriaLogsDatasource
                        name: victoria-logs-nekropolis-proxy
                    field: kubernetes.pod_namespace
                    query: '*'

kind: ConfigMap
metadata:
  name: perses-provisioning-gk74d2fg52
  namespace: perses
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: networking
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: perses
    app.kubernetes.io/name: perses
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: workload
    app.kubernetes.io/instance: perses
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/version: v0.53.1
    helm.sh/chart: perses-0.21.0
  name: perses
  namespace: perses
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: perses
      app.kubernetes.io/name: perses
  serviceName: perses-headless
  template:
    metadata:
      annotations:
        checksum/config: a42758114e7e69cab7a33207a98d64c7165d46488331d7cc5c1bc4c66e1f6622
      labels:
        app.kubernetes.io/instance: perses
        app.kubernetes.io/name: perses
    spec:
      containers:
      - args:
        - --config=/etc/perses/config/config.yaml
        - --web.listen-address=:8080
        - --web.hide-port=false
        - --web.telemetry-path=/metrics
        - --log.level=info
        - --log.method-trace=true
        env:
        - name: PERSES_SECURITY_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: perses-security-encryption-key
              name: perses
        image: docker.io/persesdev/perses:v0.53.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: perses
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/perses/provisioning
          name: perses-provisioning
        - mountPath: /etc/perses/config
          name: config
        - mountPath: /perses
          name: data
      securityContext:
        fsGroup: 2000
      serviceAccountName: perses
      volumes:
      - configMap:
          name: perses-provisioning-gk74d2fg52
        name: perses-provisioning
      - emptyDir: {}
        name: data
      - configMap:
          defaultMode: 420
          name: perses
        name: config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: perses
  namespace: perses
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/nekropolis/perses/perses
      metadataPolicy: None
      property: PERSES_SECURITY_ENCRYPTION_KEY
    secretKey: perses-security-encryption-key
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: perses
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    kube-vip.io/loadbalancerIPs: 192.168.13.10
  name: perses
  namespace: perses
spec:
  ingressClassName: cilium
  rules:
  - host: perses.nekropolis.irminsul
    http:
      paths:
      - backend:
          service:
            name: perses
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - perses.nekropolis.irminsul
    secretName: perses-certificate
